[package]
name = "iroh-services"
version = "1.0.0"
edition = "2024"
readme = "../README.md"
description = "p2p quic connections dialed by public key"
license = "MIT OR Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh-services"
keywords = ["quic", "networking", "holepunching", "p2p"]
rust-version = "1.91"

[dependencies]
data-encoding = "2.9.0"
ed25519-dalek = { version = "=3.0.0-rc.0" }
irpc = { version = "0.17", default-features = false, features = ["derive", "stream", "spans"] }
irpc-iroh = "0.17"
iroh = { version = "1.0.0", default-features = false, features = ["unstable-net-report"] }
iroh-metrics = { version = "1.0.0", default-features = false }
iroh-services-proto = { version = "0.1.0", path = "../iroh-services-proto" }
iroh-tickets = "1.0.0"
n0-error = "1.0.0"
n0-future = "0.3"
postcard = { version = "1.1.3", features = ["use-std"] }
rcan = "0.4"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1", default-features = false, features = ["sync"] }
tokio-util = { version = "0.7", default-features = false }
tracing = "0.1.41"
uuid = { version = "1.17", features = ["v4", "serde", "v7", "js"] }
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "fmt",
    "json",
] }
serde_json = "1.0.140"
bytes = { version = "1.10.1", features = ["serde"] }
futures-buffered = "0.2.12"
rand = "0.10.1"

[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dependencies]
base64 = "0.22"
portmapper = "0.19"

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }

[build-dependencies]
built = { version = "0.8", features = ["cargo-lock"] }
cfg_aliases = "0.2.1"

[dev-dependencies]
rand = { version = "0.10", features = ["chacha"] }

[target.'cfg(not(all(target_family = "wasm", target_os = "unknown")))'.dev-dependencies]
temp_env_vars = "0.2.1"
tokio = { version = "1.45", features = ["macros", "rt", "rt-multi-thread", "signal"] }

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dev-dependencies]
wasm-bindgen-test = "0.3.75"


[features]
default = []

[[example]]
name = "net_diagnostics"

[[test]]
name = "integration"
path = "tests/integration.rs"

[package.metadata.cargo_check_external_types]
allowed_external_types = [
    # We use iroh's NetReport type on the wire. Note that this type
    # is under iroh's unstable-net-report feature, which means it can break at any time.
    # If it does break, we need to release a new major version of iroh-services
    # and disallow older iroh versions.
    "iroh::net_report::report::Report",
    # Remaining stable iroh types
    "iroh::endpoint::ConnectError",
    "iroh::endpoint::Endpoint",
    "iroh::endpoint::RelayMode",
    "iroh::endpoint::presets::Preset",
    "iroh::protocol::ProtocolHandler",
    # 1.0 crates without unstable features
    "iroh_base::*",
    "iroh_relay::*",
    "iroh_metrics::*",
    "iroh_tickets::*",
    "n0_error",
    "n0_error::*",
    "serde_core::*",
    "tokio::sync::mpsc::error::SendError",
    "tokio::sync::oneshot::error::RecvError"
]
