name: wasm

on:
  pull_request:
    types: ["labeled", "unlabeled", "opened", "synchronize", "reopened"]
  merge_group:
  push:
    branches:
      - main

# Default to read-only; jobs that need more grant it explicitly.
permissions:
  contents: read

jobs:
  wasm_test:
    name: Build & test wasm32 for browsers
    timeout-minutes: 5
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup node.js version 26 # need at least version 22.5 for running iroh
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen-test-runner
        uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # v2.85.11
        with:
          # Match the version of wasm-bindgen used in Cargo.lock
          tool: wasm-bindgen-cli@0.2.125

      - name: Run integration test in wasm
        run: cargo test --locked --test integration --target=wasm32-unknown-unknown
        env:
          RUST_LOG: iroh_services=trace
          IROH_SERVICES_API_SECRET: ${{ secrets.IROH_SERVICES_API_SECRET }}
